version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - v1-dependencies-{{ .Branch }}
          - v1-dependencies

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run:
          name: "Lint Javascript"
          command: |
            node_modules/.bin/eslint .

      - run:
          name: "Lint Styles"
          command: |
            node_modules/.bin/stylelint ./**/*.css
  deploy:
    docker:
      - image: circleci/node:6-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - v1-dependencies-{{ .Branch }}
          - v1-dependencies

      - run:
          name: "Deploy to development"
          command: |
            if [ "${CIRCLE_BRANCH}" == "development" ]; then
              ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null bluediamond@planetary.io '. ~/.profile && ~/development/redeploy'
            fi;

      - run:
          name: "Deploy to staging"
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null bluediamond@planetary.io '. ~/.profile && ~/staging/redeploy'
            fi;

      - run:
          name: "Deploy to production"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null site@45.55.190.115 '~/redeploy'
              ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null site@45.55.205.47 '~/redeploy'
            fi;

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
